### PR TITLE
Added convert command!

### PR DESCRIPTION
**Pull request by ghost**
Added some convert command :) Imma send the images later and btw they can use it by doing
```js
 const { convert } = require("weky")

if (args[0] == 'C') {
convert('C', args, message);
} else if (args[0] == 'F') {
 convert('F', args, message);
} else {
message.channel.send('You have to choose C or F!');
}
```

### CODE REVIEW

**Comment by face-hh** [comment]
useless :|

**Comment by ghost** [comment]
ok

**Comment by ghost** [comment]
what should i make :(

**Comment by KainesLaw** [comment]
> useless :|

face is being ruthless

**Pull request closed without merging**
