### PR TITLE
<:kek:830066746882523177>

### PR DESCRIPTION
**Pull request by adambrangenberg**
I've updated some of the "commands" to v13 because I took long and I was bored lol (the new version isn't included)

You probably need to create a new branch to make the commit compatible =)

### CODE REVIEW

**Comment by adambrangenberg** [comment]
(If you create the branch may I need to remake the pull request into it or pull it into main never did it with different branches 😃 )

**Comment by sujalgoel** [comment]
I looked into your code and their are few things, which needs to be changed. So, We will update the files locally and then later push it

**Comment by adambrangenberg** [comment]
> I looked into your code and their are few things, which needs to be changed. So, We will update the files locally and then later push it

Okay

**Comment by RaZeSloth** [comment]
My guy literally replaced `discord-buttons` with `discord.js`. And he has he's token in the code 😂

**Comment by sujalgoel** [comment]
<:kek:830066746882523177>

**Comment by adambrangenberg** [comment]
> My guy literally replaced `discord-buttons` with `discord.js`. And he has he's token in the code 😂

As I said I didn't edit everything.... But you probably can't read otherwise you would just dumb and rude. I don't want to believe that. Also the Token of my Testbot resetts automaticlly so idc

**Comment by RaZeSloth** [comment]
> > My guy literally replaced `discord-buttons` with `discord.js`. And he has he's token in the code joy
> 
> As I said I didn't edit everything.... But you probably can't read otherwise you would just dumb and rude. I don't want to believe that. Also the Token of my Testbot resetts automaticlly so idc

Sorry to burst the bubble sweetheart, but it just doesn't work like that :)

**Comment by adambrangenberg** [comment]
> > > My guy literally replaced `discord-buttons` with `discord.js`. And he has he's token in the code joy
> > 
> > As I said I didn't edit everything.... But you probably can't read otherwise you would just dumb and rude. I don't want to believe that. Also the Token of my Testbot resetts automaticlly so idc
> 
> Sorry to burst the bubble sweetheart, but it just doesn't work like that :)

Such a meme 😂😂😂

**Comment by RaZeSloth** [comment]
This is a closed pr sir

**Comment by adambrangenberg** [comment]
> This is a closed pr sir

I just saying =)

**Pull request closed without merging**
