### PR TITLE
Added slots class!

### PR DESCRIPTION
**Pull request by ghost**
Added slots class! Which they can use it with 

```js
const weky = require("weky")

var slot = new weky.Slots({
    message: message,
    winMessage: "Nice, You've won the slots!",
    loseMessage: "Lmao, better next time",
    emojiOne: "some emoji 1",
    emojiTwo: "some emoji 2",
    emojiThree: "some emoji 3"
})

slot.start()
```

### CODE REVIEW

**Comment by ghost** [comment]
Btw i will use embed soon so they can send an embed if they want :)

**Comment by sujalgoel** [comment]
We will check it and if found useful then will use your code in the next update!

**Comment by face-hh** [comment]
can you attach a preview?

**Comment by ghost** [comment]
hm ok

**Comment by ghost** [comment]
loseMessage
image

**Comment by ghost** [comment]
winMessage
image

**Comment by face-hh** [comment]
seems good

**Comment by ghost** [comment]
I will add an embed soon

**Comment by ghost** [comment]
Wait so im gonna delete the branch right?

**Comment by face-hh** [comment]
ye

**Comment by ghost** [comment]
ok thx!

**Pull request merged**
