### PR TITLE
Using buttons instead of reactions in accept message [fight]

### PR DESCRIPTION
**Pull request by Assassin-1234**
why even use reactions

OSzSppuD

### CODE REVIEW

**Comment by sujalgoel** [comment]
gg! I was about to work on it but you made my work easier! Thanks 👍

**Comment by Assassin-1234** [comment]
np :)

**Comment by Assassin-1234** [comment]
can I close this if its not getting merged 😳

**Comment by sujalgoel** [comment]
ye

**Comment by sujalgoel** [comment]
you can just close this! We will credit you.

**Comment by Assassin-1234** [comment]
ight thanks

**Pull request closed without merging**
